

- name: Download Elasticsearch GPG key
  get_url:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    dest: /tmp/GPG-KEY-elasticsearch
    mode: '0644'

- name: Convert GPG key and store it
  command:
    cmd: gpg --batch --yes --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg /tmp/GPG-KEY-elasticsearch

- name: "Install the apt-transport-https"
  apt:
    name: apt-transport-https
    state: present

- name: Add Elasticsearch APT repository
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main'
    state: present
    filename: elastic-8.x

- name: Update APT package cache
  ansible.builtin.apt:
    update_cache: yes
  
- name: Install Kibana
  apt: 
    name: kibana={{ elk_version }}
    state: present
  register: install_output
  when: "'elasticsearch_kibana' in group_names"

- name: "Update kibana.yaml file"
  template: 
    src: kibana.yml
    dest: /etc/kibana/kibana.yml

- name: Enable and Start kibana
  ansible.builtin.service:
    name: kibana
    enabled: yes
    state: started
  when: "'elasticsearch_kibana' in group_names"


