---
- name: Install Kibana
  apt: 
    name: kibana={{ elk_version }}
    state: present
  register: install_output
  when: "'elasticsearch_kibana' in group_names"

- name: "Update kibana.yaml file"
  template: 
    src: kibana.yml
    dest: /etc/kibana/kibana.yml

- name: Enable and Start kibana
  ansible.builtin.service:
    name: kibana
    enabled: yes
    state: started
  when: "'elasticsearch_kibana' in group_names"

- name: Wait for Kibana verification code to appear in logs
  ansible.builtin.shell: journalctl -u kibana --no-pager | grep "verification code"
  register: kibana_verification_code
  retries: 50
  delay: 10
  until: kibana_verification_code.stdout != ""
  changed_when: false


- name: Show Kibana verification code
  ansible.builtin.debug:
    var: kibana_verification_code.stdout
