
- name: Common Setup
  import_tasks:
    file: common.yml

- name: Elasticsearch Configuration
  import_tasks: 
    file: elastic-config.yml
  when: "'elasticsearch_kibana' not in group_names"

- name: Kibana Configuration 
  import_tasks: 
    file: kibana-config.yml
  when: "'elasticsearch_kibana' in group_names"
